# Generated by Django 2.0.1 on 2018-02-27 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalproduct',
            old_name='pid',
            new_name='itemID',
        ),
        migrations.RenameField(
            model_name='rentalproduct',
            old_name='max_rental_days',
            new_name='maxRental',
        ),
        migrations.RenameField(
            model_name='rentalproduct',
            old_name='retire_date',
            new_name='retireDate',
        ),
    ]
